# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam Hermes
description: Front-end web developer at Washington University in St. Louis. Writes about CSS, JavaScript, accessibility, WordPress, and more.
url: "https://samhermes.com"
permalink: /posts/:title/

# Build settings
markdown: kramdown
sass:
  style: compressed

# Add custom collections
collections:
  photos:
  projects:
  lists:
    output: true
  category:
    output: true