---
title: Sam Hermes
timezone: UTC
collections:
  photos:
    title: Photos
    output: false
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  lists:
    title: Lists
    output: true
  category:
    title: Category
    output: true
  uploads:
    title: Uploads
    output: true
description: Front-end web developer in St. Louis. Writes about CSS, WordPress, JavaScript,
  accessibility, and more.
url: https://samhermes.com
permalink: "/posts/:title/"
markdown: kramdown
sass:
  style: compressed
