---
title: Sam Hermes
timezone: UTC
collections:
  category:
    title: Category
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
description: Front-end developer focused on CSS, accessibility, and UX.
url: https://samhermes.com
permalink: "/posts/:title/"
markdown: kramdown
sass:
  style: compressed
