# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam Hermes
description: Front-end web developer at Washington University in St. Louis. Writes about CSS, JavaScript, accessibility, WordPress, and more.
url: "https://samhermes.com"
permalink: /posts/:title/

# Build settings
markdown: kramdown
sass:
  style: compressed
exclude: ['next-spacex-launch/node_modules']
keep_files: ['next-spacex-launch/node_modules']

plugins:
  - jekyll-archives

# Add custom collections
collections:
  photos:
  projects:
  lists:
    output: true

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'