# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sam Hermes
email: your-email@domain.com
description: Web developer at Washington University in St. Louis
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://samhermes.com" # the base hostname & protocol for your site
permalink: /posts/:title/

# Build settings
markdown: kramdown
