# Site settings
title: Sam Hermes
url: "http://samhermes.com"
twitter_username: samhermes
github_username:  samhermes

# Build settings
markdown: kramdown

# Outputting
permalink: /:categories/:title/

exclude: ["node_modules", "aws.json", "gulpfile.js"]