---
title: Sam Hermes
timezone: UTC
collections:
  category:
    title: Category
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
description: Sam is a front-end web developer in Chicago, and writes about CSS, WordPress,
  JavaScript, accessibility, and more.
url: https://samhermes.com
permalink: "/posts/:title/"
markdown: kramdown
sass:
  style: compressed
defaults:
-
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: "default"
